# Generated by Django 3.1.4 on 2021-01-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgit',
            old_name='item',
            new_name='description',
        ),
    ]
